# Generated by Django 5.0.3 on 2024-05-11 03:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_lookbook_master'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категория цен', 'verbose_name_plural': 'Категории цен'},
        ),
        migrations.AlterModelOptions(
            name='master',
            options={'ordering': ('title',), 'verbose_name': 'Мастер', 'verbose_name_plural': 'Мастера'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('title',), 'verbose_name': 'Цена на услугу', 'verbose_name_plural': 'Цены на улсуги'},
        ),
        migrations.RemoveField(
            model_name='master',
            name='image',
        ),
        migrations.CreateModel(
            name='MasterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/thumbnails/unnamed.jpg', upload_to='master_images/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))])),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.master')),
            ],
            options={
                'verbose_name': 'Фотография работ мастера',
                'verbose_name_plural': 'Фотографии работ мастера',
                'ordering': ('master',),
            },
        ),
    ]
