# Generated by Django 5.0.3 on 2024-05-19 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_service_price'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='service',
            index_together={('id',)},
        ),
        migrations.RemoveField(
            model_name='service',
            name='slug',
        ),
    ]
